spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/batch_db
    username: batch_user
    password: batch_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  logging:
    level:
      com.realworldjava.batchprocessing: INFO
