spring:
  application:
    name: secure-rest-api-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/demo
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

logging:
  level:
    root: INFO
    com.realworldjava.securerestapi.server: DEBUG
