version: '3.8'

services:
  db:
    image: postgres:17
    container_name: batch-postgres
    environment:
      POSTGRES_USER: batch_user
      POSTGRES_PASSWORD: batch_pass
      POSTGRES_DB: batch_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U batch_user" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: