services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    command: [ "start-dev", "--import-realm" ]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/config.json
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    ports:
      - "8081:8080"
    volumes:
      - ./realm-config:/opt/keycloak/data/import
