name: Build and SonarCloud

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and run tests
        run: mvn clean verify
