name: Test Branch Build

on:
  pull_request:
    branches: [ test ]

permissions:
  contents: read

jobs:
  build-test-branch:
    runs-on: ubuntu-latest

    env:
      TEST_SECRET: ${{ secrets.TEST_SECRET }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and run tests with Maven
        run: ./mvnw clean verify
